cities = [
"Mournhold",
"Ebonheart",
"Holamayan",
"Vivec",
"Arena Canton",
"Foreign Quarter",
"Hlaalu Canton",
"Telvanni Canton",
"Temple Canton",
"Tel Branora",
"Seyda Neen",
"Hla Oad",
"Suran",
"Molag Mar",
"Balmora",
"Sadrith Mora",
"Gnaar Mok",
"Caldera",
"Tel Aruhn",
"Ald'ruhn",
"Gnisis",
"Maar Gan",
"Khuul",
"Raven Rock",
"Fort Frostmoth",
"Raven Rock",
"Dagon Fel",
"Tel Mora",
"Vos"
]

transport_methods = enumerate([
  "Silt Strider",
  "Boat",
  "Guild Guide",
  "Gondola",
  ])

# Weighted Edges: (starting, ending, time, type, npc, location)
edges = [
("Mournhold", "Ebonheart", 0, 2),
("Ebonheart", "Mournhold", 0, 2),
("Ebonheart", "Vivec", 1, 1),
("Ebonheart", "Tel Branora", 6, 1),
("Ebonheart", "Sadrith Mora", 11, 1),
("Ebonheart", "Hla Oad", 5, 1),
("Ebonheart", "Holamayan", 9, 1),
("Holamayan", "Ebonheart", 9, 1),
("Vivec", "Ebonheart", 1, 1),
("Vivec", "Tel Branora", 5, 1),
("Vivec", "Molag Mar", 4, 1),
("Vivec", "Molag Mar", 4, 0),
("Vivec", "Seyda Neen", 2, 0),
("Vivec", "Suran", 1, 0),
("Vivec", "Hla Oad", 5, 1),
("Arena Canton", "Foreign Quarter", 0, 3),
("Arena Canton", "Hlaalu Canton", 0, 3),
("Arena Canton", "Telvanni Canton", 0, 3),
("Arena Canton", "Temple Canton", 0, 3),
("Foreign Quarter", "Arena Canton", 0 , 3),
("Foreign Quarter", "Hlaalu Canton", 0 , 3),
("Foreign Quarter", "Telvanni Canton", 0 , 3),
("Hlaalu Canton", "Arena Canton", 0 , 3),
("Hlaalu Canton", "Foreign Quarter", 0 , 3),
("Hlaalu Canton", "Temple Canton", 0 , 3),
("Telvanni Canton", "Arena Canton", 0 , 3),
("Telvanni Canton", "Foreign Quarter", 0 , 3),
("Telvanni Canton", "Temple Canton", 0 , 3),
("Temple Canton", "Arena Canton", 0 , 3),
("Temple Canton", "Hlaalu Canton", 0 , 3),
("Temple Canton", "Telvanni Canton", 0 , 3),
("Tel Branora", "Molag Mar", 2, 1),
("Tel Branora", "Vivec", 5, 1),
("Tel Branora", "Sadrith Mora", 8, 1),
("Seyda Neen","Vivec",2, 0),
("Seyda Neen","Suran",4, 0),
("Seyda Neen","Balmora",3, 0),
("Seyda Neen","Gnisis",11, 0),
("Hla Oad","Vivec",5, 1),
("Hla Oad","Ebonheart",5, 1),
("Hla Oad","Molag Mar",10, 1),
("Hla Oad","Gnaar Mok",4, 1),
("Suran","Molag Mar",3, 0),
("Suran","Vivec",1, 0),
("Suran","Seyda Neen",4,0),
("Suran","Balmora",5,0),
("Molag Mar","Tel Branora",2, 1),
("Molag Mar","Hla Oad",10, 1),
("Molag Mar","Vivec",4, 0),
("Molag Mar","Vivec", 4, 1),
("Molag Mar","Suran",3, 0),
("Balmora","Suran",5, 1),
("Balmora","Vivec",4,1),
("Balmora","Seyda Neen",3,1),
("Balmora","Ald'ruhn",4,1),
("Sadrith Mora", "Tel Mora",5,1),
("Sadrith Mora", "Dagon Fel", 10,1),
("Sadrith Mora", "Ebonheart", 11,1),
("Sadrith Mora", "Tel Branora", 8,1),
("Gnaar Mok", "Hla Oad", 4, 1),
("Gnaar Mok", "Khuul", 7, 1),
("Tel Aruhn", "Tel Mora", 4, 1),
("Tel Aruhn", "Dagon Fel", 9, 1),
("Tel Aruhn", "Vos", 4, 1),
("Ald'ruhn","Maar Gan",2,0),
("Ald'ruhn","Gnisis",4,0),
("Ald'ruhn","Khuul",5,0),
("Ald'ruhn","Balmora",4,0),
("Gnisis", "Khuul", 3,0),
("Gnisis", "Maar Gan", 4,0),
("Gnisis", "Ald'ruhn", 4,0),
("Gnisis", "Seyda Neen", 11,0),
("Maar Gan","Ald'ruhn",2,0),
("Maar Gan","Khuul",4,0),
("Maar Gan","Gnisis",3,0),
("Khuul","Maar Gan",3,0),
("Khuul","Ald'ruhn",5,0),
("Khuul","Gnisis",7,0),
("Khuul","Gnaar Mok",7,1),
("Khuul","Fort Frostmoth",6,1),
("Khuul","Dagon Fel",8,1),
("Fort Frostmoth", "Khuul", 6, 1),
("Fort Frostmoth", "Raven Rock", 2,1),
("Raven Rock", "Fort Frostmoth", 2,1),
("Dagon Fel","Khuul",8,1),
("Dagon Fel","Sadrith Mora",10,1),
("Dagon Fel","Tel Aruhn",9,1),
("Dagon Fel","Tel Mora",5,1),
("Tel Mora","Tel Aruhn",4,1),
("Tel Mora","Sadrith Mora",5,1),
("Tel Mora","Vos",0,1),
("Tel Mora","Dagon Fel",5,1),
("Vos", "Tel Mora", 0,1),
("Vos", "Sadrith Mora", 5,1),
("Vos", "Tel Aruhn", 4,1),
("Caldera", "Ald'ruhn",0,2),
("Caldera", "Sadrith Mora",0,2),
("Caldera", "Vivec",0,2),
("Caldera", "Balmora",0,2),
("Ald'ruhn", "Sadrith Mora",0,2),
("Ald'ruhn", "Vivec",0,2),
("Ald'ruhn", "Balmora",0,2),
("Ald'ruhn", "Caldera",0,2),
("Sadrith Mora", "Vivec",0,2),
("Sadrith Mora", "Balmora",0,2),
("Sadrith Mora", "Caldera",0,2),
("Sadrith Mora", "Ald'ruhn",0,2),
("Vivec", "Balmora",0,2),
("Vivec", "Caldera",0,2),
("Vivec", "Ald'ruhn",0,2),
("Vivec", "Sadrith Mora",0,2),
("Balmora", "Caldera",0,2),
("Balmora", "Ald'ruhn",0,2),
("Balmora", "Sadrith Mora",0,2),
("Balmora", "Vivec",0,2),
]


