cities = [
"Ebonheart",
"Vivec",
"Tel Branora",
"Seyda Neen",
"Hla Oad",
"Suran",
"Molag Mar",
"Balmora",
"Sadrith Mora",
"Gnaar Mok",
"Caldera",
"Tel Aruhn",
"Ald'ruhn",
"Gnisis",
"Maar Gan",
"Khuul",
"Fort Frostmoth",
"Dagon Fel",
"Tel Mora",
"Vos"
]

# Weighted Edges: (starting, ending, weight)
edges = [
("Ebonheart", "Vivec", 1),
("Ebonheart", "Tel Branora", 6),
("Ebonheart", "Sadrith Mora", 11),
("Ebonheart", "Hla Oad", 5),
("Vivec", "Ebonheart", 1),
("Vivec", "Tel Branora", 5),
("Vivec", "Molag Mar", 4),
("Vivec", "Seyda Neen", 2),
("Vivec", "Suran", 1),
("Vivec", "Hla Oad", 5),
("Tel Branora", "Molag Mar", 2),
("Tel Branora", "Vivec", 5),
("Tel Branora", "Sadrith Mora", 8),
("Seyda Neen","Vivec",2),
("Seyda Neen","Suran",4),
("Seyda Neen","Balmora",3),
("Seyda Neen","Gnisis",11),
("Hla Oad","Vivec",5),
("Hla Oad","Ebonheart",5),
("Hla Oad","Molag Mar",10),
("Hla Oad","Gnaar Mok",4),
("Suran","Molag Mar",3),
("Suran","Vivec",1),
("Suran","Seyda Neen",4),
("Suran","Balmora",5),
("Molag Mar","Tel Branora",2),
("Molag Mar","Hla Oad",10),
("Molag Mar","Vivec",4),
("Molag Mar","Suran",3),
("Balmora","Suran",5),
("Balmora","Vivec",4),
("Balmora","Seyda Neen",3),
("Balmora","Ald'ruhn",4),
("Sadrith Mora", "Tel Mora", 5),
("Sadrith Mora", "Dagon Fel", 10),
("Sadrith Mora", "Ebonheart", 11),
("Sadrith Mora", "Tel Branora", 8),
("Gnaar Mok", "Hla Oad", 4),
("Gnaar Mok", "Khuul", 7),
("Tel Aruhn", "Tel Mora", 4),
("Tel Aruhn", "Dagon Fel", 9),
("Tel Aruhn", "Vos", 4),
("Ald'ruhn","Maar Gan",2),
("Ald'ruhn","Gnisis",4),
("Ald'ruhn","Khuul",5),
("Ald'ruhn","Balmora",4),
("Gnisis", "Khuul", 3),
("Gnisis", "Maar Gan", 4),
("Gnisis", "Ald'ruhn", 4),
("Gnisis", "Seyda Neen", 11),
("Maar Gan","Ald'ruhn",2),
("Maar Gan","Khuul",4),
("Maar Gan","Gnisis",3),
("Khuul","Maar Gan",3),
("Khuul","Ald'ruhn",5),
("Khuul","Gnisis",7),
("Khuul","Gnaar Mok",7),
("Khuul","Fort Frostmoth",),
("Khuul","Dagon Fel",8),
("Fost Frostmoth", "Khuul", 6),
("Dagon Fel","Khuul",8),
("Dagon Fel","Sadrith Mora",10),
("Dagon Fel","Tal Aruhn",9),
("Dagon Fel","Tel Mora",5),
("Tel Mora","Tel Aruhn",4),
("Tel Mora","Sadrith Mora",5),
("Tel Mora","Vos",0),
("Tel Mora","Dagon Fel",5),
("Vos", "Tel Mora", 0),
("Vos", "Sadrith Mora", 5),
("Vos", "Tel Aruhn", 4)
]


